# Exercise 2.A Fundamentals of pandas

In [1]:
import numpy as np
import pandas as pd

## Series

In [2]:
# Different Python data types

aa = [1, 2, 3, 4]

ab = (5, 6, 7, 8)

ac = {9, 10, 11, 12}

ad = {
    "first": 13,
    "second": 14,
    "third": 15,
    "fourth": 16
}

In [3]:
# Turn the Python objects into pandas Series

ser1 = pd.Series(aa)
ser2 = pd.Series(ab)
ser3 = pd.Series(list(ac))
ser4 = pd.Series(ad)

print(ser1)
print()

print(ser2)
print()

print(ser3)
print()

print(ser4)

0    1
1    2
2    3
3    4
dtype: int64

0    5
1    6
2    7
3    8
dtype: int64

0     9
1    10
2    11
3    12
dtype: int64

first     13
second    14
third     15
fourth    16
dtype: int64

In [4]:
# This gives an error because the values are not written correctly

ser5 = pd.Series(17, 18, 19, 20)

# TypeError: Series.__init__() takes from 1 to 4 positional arguments but 5 were given

TypeError: Index(...) must be called with a collection of some kind, 18 was passed

## DataFrames from Series

In [5]:
# Create a DataFrame from ser1

df1 = pd.DataFrame(ser1)

df1

   0
0  1
1  2
2  3
3  4

In [6]:
# Add new columns using insert()

df1.insert(1, "Second", ser2)

df1.insert(2, "Third", ser3)

df1

   0  Second  Third
0  1       5      9
1  2       6     10
2  3       7     11
3  4       8     12

In [7]:
# Add another column using ser4

df1["Fourth"] = ser4

df1

# ser4 uses words as indexes like first and second.
# The other Series use number indexes like 0,1,2,3.
# Because the indexes do not match, pandas shows NaN values.

   0  Second  Third  Fourth
0  1       5      9     NaN
1  2       6     10     NaN
2  3       7     11     NaN
3  4       8     12     NaN

In [8]:
# Add a new row using loc

df1.loc[4] = [5, 9, 12, 0]

df1

   0  Second  Third  Fourth
0  1       5      9     NaN
1  2       6     10     NaN
2  3       7     11     NaN
3  4       8     12     NaN
4  5       9     12     0.0

## Reading Data into a DataFrame

In [9]:
# Read the CSV file

df2 = pd.read_csv("sakila_example.csv")

df2

FileNotFoundError: [Errno 2] No such file or directory: 'sakila_example.csv'

In [ ]:
# Show first 5 rows

df2.head()

In [10]:
# Show last 10 rows

df2.tail(10)

NameError: name 'df2' is not defined

In [11]:
# Show information about the data

df2.info()

NameError: name 'df2' is not defined

The info() results show the number of rows and columns.  
It also shows the column names, data types, and missing values.

In [12]:
# Show statistics for number columns

df2.describe()

NameError: name 'df2' is not defined

The describe() results help show averages, minimum values, and maximum values.  
This makes it easier to understand the data.  
Some columns may not be very useful if they only contain ID numbers.

In [ ]:
# Read another CSV file

df3 = pd.read_csv("northwind_example.csv")

df3

In [17]:
# Show statistics for df3

df3.describe()

NameError: name 'df3' is not defined

The statistics for df3 may look different because the data is different.  
Some columns may have larger numbers or different ranges compared to df2.

## Coding a DataFrame

In [13]:
# Create dictionary data

test_data = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8],

    "Name": ["Alicia", "Bob", "Charlie", "Dominic",
             "Eve", "Frank", "Grace", "Heidi"],

    "Age": [25, np.nan, 22, 19, 31, 35, np.nan, 18],

    "City": ["NY", "LA", "Chicago", "Houston",
             "Phoenix", "Boston", "Austin", "San Diego"],

    "Score": [85, 92, -1, 65, 78, np.nan, 55, 90]
}

In [14]:
# Create DataFrame

df4 = pd.DataFrame(test_data)

df4

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [15]:
# Export to CSV file

df4.to_csv("test_data.csv", index=False)